# Docker environment for local development
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.1.1
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    expose:
      - 2181

  kafka:
    expose:
      - 9092
      - 8082
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    image: confluentinc/cp-kafka:3.1.1
    depends_on:
      - zookeeper

  schema-registry:
    image: confluentinc/cp-schema-registry:3.1.1
    expose:
      - 8081
    environment:
        - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
        - SCHEMA_REGISTRY_HOST_NAME=schema-registry
        - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081
        - SCHEMA_REGISTRY_DEBUG=true
    depends_on:
      - kafka
      - zookeeper

  db:
    image: postgres:9.5.3
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=finops_admin_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=

  kafka-tools:
    image: confluentinc/cp-kafka:3.1.1
    depends_on:
      - zookeeper
      - schema-registry
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
    working_dir: /usr/src/app
    entrypoint: /bin/bash

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.finops-admin.yml
    image: quay.io/fundingcircle/finops-admin:dev
    depends_on:
      - kafka
      - schema-registry
      - zookeeper
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - ARTIFACTORY_USER=${ARTIFACTORY_USER}
      - ARTIFACTORY_PASSWORD=${ARTIFACTORY_PASSWORD}
    working_dir: ${PWD}
    ports:
      - ${NREPL_PORT}:${NREPL_PORT}
      - 3449:3449
    volumes:
      - .:${PWD}
    entrypoint: lein with-profile +docker-nrepl repl :headless :host 0.0.0.0 :port ${NREPL_PORT}
